version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.config.file=/etc/prometheus/web-config.yml"
      - "--web.enable-lifecycle"
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring

    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring
  
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    networks:
      - monitoring
  
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    ports:
      - "9116:9116"
      - "161:161/udp"
    volumes:
      - ./snmp_exporter:/etc/snmp-exporter
    commnad:
      - --config.file=/etc/snmp-exporter/snmp.yml
    networks:
      - monitoring

volumes:
  prometheus_data:
  prometheus_config:
  grafana_storage:
  alertmanager_config:
  alertmanager_data:

networks:
  monitoring:
    driver: bridge