version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.config.file=/etc/prometheus/web-config.yml"
      - "--web.enable-lifecycle"
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/node_exporter.yml:/etc/prometheus/node_exporter.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/web-config.yml:/etc/prometheus/web-config.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  prometheus_data:
  prometheus_config:
  grafana_storage: