version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.config.file=/etc/prometheus/web.yml"
      - "--web.enable-lifecycle"
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus
    ports:
      - "9090:9090"

volumes:
  prometheus_data:
  prometheus_config: