# my global config
global:
  scrape_interval: 10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    - static_configs:
        - targets:
          - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'Linux'
    basic_auth:
      username: 'Nghi'
      password: 'nghi'
    static_configs:
    - targets: 
      - '10.0.30.72:9100'
      - '10.0.30.236:9100'
  - job_name: 'Windows'
    static_configs:
    - targets: 
      - '10.0.30.254:9100'
