# scrape_configs.yml
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'node_exporter'
  static_configs:
    - targets: ['node1.example.com:9100', 'node2.example.com:9100']
